# Generated by Django 4.2.17 on 2026-04-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterIndexTogether(
            name='task',
            index_together={('status', 'priority')},
        ),
    ]
